### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ff98sha** [Teahouse-Studios/mcwzh-meme-resourcepack-bedrock#11]
I, ff98sha, hereby give special license "[CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)" of [mclangcn](https://github.com/ff98sha/mclangcn)  to 
[mcwzh-meme-resourcepack-bedrock](https://github.com/Teahouse-Studios/mcwzh-meme-resourcepack-bedrock) from now.

**Comment by Dianliang233** [comment]
thanc u, thanc u veri much
