### ISSUE TITLE
我对梗体中文的一些修改

### ISSUE THREAD

**Issue by RxinnotRstar** [Teahouse-Studios/mcwzh-meme-resourcepack-bedrock#12]
我修改了一些语言文件的内容，希望作者愿意接纳
修改后的语言文件：
https://rxinns.lanzoui.com/iRCjMivfqyj
以下是一小部分修改内容。
![截屏_2020-11-27-00-47-03](https://user-images.githubusercontent.com/56676566/100520004-6f991d80-31d6-11eb-8250-a4b0348e0b04.png)
![截屏_2020-11-27-00-54-59](https://user-images.githubusercontent.com/56676566/100520010-7de73980-31d6-11eb-88e4-0d54aaaef4c3.png)
![截屏_2020-11-27-01-02-24](https://user-images.githubusercontent.com/56676566/100520023-9a837180-31d6-11eb-9fc7-04040f1f986c.png)
![截屏_2020-11-27-14-25-02](https://user-images.githubusercontent.com/56676566/100520039-b7b84000-31d6-11eb-9f0e-46441104e50a.png)

**Comment by XxLittleCxX** [comment]
请问你是按照哪个commit的zh_ME.lang进行的修改，看到diff有一些不对劲。

**Comment by XxLittleCxX** [comment]
[zh_ME.lang_Rx_edited.txt](https://github.com/Teahouse-Studios/mcwzh-meme-resourcepack-bedrock/files/5610877/zh_ME.lang_Rx_edited.txt)

👆一份文件存档。

**Comment by RxinnotRstar** [comment]
基于基岩版 默认的附加内容修改的

**Comment by SkyEye-FAST** [comment]
> 
> 
> 基于基岩版 默认的附加内容修改的

嗯？你是不是很久以前下了一份改的

**Comment by XxLittleCxX** [comment]
> > 基于基岩版 默认的附加内容修改的
> 
> 嗯？你是不是很久以前下了一份改的

如果是的话，建议找一下下载时间，方便合并内容（虽然也不会方便到哪去）

**Comment by RxinnotRstar** [comment]
我使用过文本编辑器的替换功能，可能会替换掉一些不能替换的东西。烦请认真检查。

**Comment by RxinnotRstar** [comment]
我使用过文本编辑器的替换功能，可能会替换掉一些不能替换的东西。烦请认真检查。

> > > 基于基岩版 默认的附加内容修改的
> > 
> > 
> > 嗯？你是不是很久以前下了一份改的
> 
> 如果是的话，建议找一下下载时间，方便合并内容（虽然也不会方便到哪去）

我不记得准确的时间了，大约是60天之内

**Comment by AlPha5130** [comment]
> 我不记得准确的时间了，大约是距今50±10天

这段时间本仓库怕是已经更新不知道多少内容了

您还不如从最新版本弄一份出来重新改

**Comment by XxLittleCxX** [comment]
https://github.com/Teahouse-Studios/mcwzh-meme-resourcepack-bedrock/commit/85b1655c6d1cf4576907e9f97d35674b3a9f1fc2 好像是根据这个commit来修改的

**Comment by RxinnotRstar** [comment]
> > 我不记得准确的时间了，大约是距今50±10天
> 
> 这段时间本仓库怕是已经更新不知道多少内容了
> 
> 您还不如从最新版本弄一份出来重新改

🉑
现在就去弄一份

**Comment by RxinnotRstar** [comment]
我改完了，新的

https://rxinns.lanzoui.com/b0b36lgpi

**Comment by XxLittleCxX** [comment]
你怎么把大量的空行和注释都删除了，这直接带来巨大的麻烦。我试试用修改内容发一个pr。

**Comment by XxLittleCxX** [comment]
```js
const fs = require('fs')

let lang = fs.readFileSync('./meme_resourcepack/texts/zh_ME.lang').toString()
const diff = fs.readFileSync('./diff.txt').toString().split("\r\n").filter(v => v && !v.startsWith("//"))

diff.forEach(v => {
    if (v.includes("→")) {
        const t = v.split("→")
        lang = lang.replace(`=${t[0]}`, `=${t[1]}`)
    } else {
        const t = v.split("↹")
        lang = lang.replace(`${t[0]}`, `${t[1]}`)
    }
})

fs.writeFileSync('./meme_resourcepack/texts/zh_ME.lang.1', lang)
```

存档：
[zh_ME.lang.change.txt](https://github.com/Teahouse-Studios/mcwzh-meme-resourcepack-bedrock/files/5658511/zh_ME.lang.change.txt)
[zh_ME.lang.修改内容一览.txt](https://github.com/Teahouse-Studios/mcwzh-meme-resourcepack-bedrock/files/5658512/zh_ME.lang.txt)

**Comment by RxinnotRstar** [comment]
> 你怎么把大量的空行和注释都删除了，这直接带来巨大的麻烦。我试试用修改内容发一个pr。

我并没有见到你说的空行和注释，我只修改了中文内容。

**Comment by XxLittleCxX** [comment]
> > 你怎么把大量的空行和注释都删除了，这直接带来巨大的麻烦。我试试用修改内容发一个pr。
> 
> 我并没有见到你说的空行和注释，我只修改了中文内容。
> 
> 我是拆mcpack包拿的zh.ME.lang文件。

emm. 我已经发到pr里面去了，请等待其他成员提供意见。

**Comment by RxinnotRstar** [comment]
> > > 你怎么把大量的空行和注释都删除了，这直接带来巨大的麻烦。我试试用修改内容发一个pr。
> > 
> > 
> > 我并没有见到你说的空行和注释，我只修改了中文内容。
> > 我是拆mcpack包拿的zh.ME.lang文件。
> 
> emm. 我已经发到pr里面去了，请等待其他成员提供意见。

好的。

我以后还会多看几遍这个语言包，阁下希望我是发送txt文件更新还是直接在issue里面回复？

**Comment by XxLittleCxX** [comment]
@RxinnotRstar 预计还有几天，其他成员才有空review，在此期间如果想要修改，可以到 https://github.com/Teahouse-Studios/mcwzh-meme-resourcepack-bedrock/pull/13 回复。
如条件允许，建议学习相关git操作方法，直接发pr。

**Comment by SkyEye-FAST** [comment]
> 
> 
> > 你怎么把大量的空行和注释都删除了，这直接带来巨大的麻烦。我试试用修改内容发一个pr。
> 
> 我并没有见到你说的空行和注释，我只修改了中文内容。
> 
> 我是拆mcpack包拿的zh.ME.lang文件。

你使用的编辑器可能保存的文件有问题，建议在电脑上使用vsc等常规编辑器来编辑文件，或者多学学Git直接给我们发Pull requests也行。
