### ISSUE TITLE
翻译失效

### ISSUE THREAD

**Issue by ThePeiLin** [Teahouse-Studios/mcwzh-meme-resourcepack-bedrock#14]
**描述**
加载材质包后在语言栏选择梗体中文后语言会变成英文

**复现步骤**
复现漏洞的步骤：

加载材质包

**版本**

* 平台：[ios 14.2]
* Minecraft 基岩版版本：[例：1.16.201]
* 资源包版本：[例：1.1.0]

**Comment by AlPha5130** [comment]
fixed in v1.1.1.
