### ISSUE TITLE
Rxin对梗体中文包的修改 #2

### ISSUE THREAD

**Issue by RxinnotRstar** [Teahouse-Studios/mcwzh-meme-resourcepack-bedrock#15]
嗨~我又来了。
干脆就把修改内容写在issue里面吧。

//格式：
//标准译名（梗体中文译名）→Rxin提供的译名

潜影盒（潜影箱）→U盘
末影箱（末影箱）→私人云盘
-终为白日：启用该设置时，夜晚永远不会降临。（-终为白日：启用该设置时，夜晚永远不会降临。）→-终为白日：启用该设置时，你将身处日不落帝国。
-昼夜更替：禁用该设置时，时间将不会流逝。（-昼夜更替：禁用该设置时，时间将不会流逝。）
→-昼夜更替：禁用该设置时，时间将砸 瓦 鲁 多。
确定（彳亍）→彳 亍
确定吗（确定吗）→彳 亍不彳 亍
我们发现你的系统启用了一个屏幕阅读器，于是自动启用了Minecraft的屏幕阅读器。（我们居然发现你的系统启用了一个屏幕阅读器，于是自动启用了Minecraft的屏幕阅读器。）→反正你的系统开了读屏，那干脆一起把Minecraft的读屏开了吧。
当猪飞的时候（当猪飞的时候）→飞 猪 旅 行
烤面包（烤面包）→烤（？）面包
石剑（石剑）→检验真理的唯一标准

更新：已经写了个pr，第一次写，如有不妥还请包涵。😀

**Comment by AlPha5130** [comment]
#16 已经关闭，如要继续改进请重开新issue。
