### ISSUE TITLE
基岩版1.17.2无法使用，显示资源包导入错误，手动添加识别不了

### ISSUE THREAD

**Issue by Leolhys** [Teahouse-Studios/mcwzh-meme-resourcepack-bedrock#20]
**描述**
请简明扼要地描述漏洞。

**复现步骤**
复现漏洞的步骤：

1. 前往“...”
2. 点击“...”
3. 滑动至“...”
4. 查看错误

**正常行为**
请简明扼要地描述应该发生的行为。

**截图**
可以的话，加上截图可以帮助解释你的问题。

**版本**

* 平台：[例：Windows 10]
* Minecraft 基岩版版本：[例：1.14.0]
* 资源包版本：[例：0.1.0]
* 环境 [例：加载了其他资源包]

**其他内容**
添加更多关于漏洞的来龙去脉。

**Comment by Leolhys** [comment]
这是ios平台，Minecraft导入梗体中文失败图像
![6BE18B3A-FDBB-40BD-9948-D6EFED8A5A55](https://user-images.githubusercontent.com/87071890/124753619-c9777800-df5b-11eb-8e48-3873f62f736a.png)
![FD9A9514-3C7A-4638-894D-E24711F7B3AB](https://user-images.githubusercontent.com/87071890/124753639-ce3c2c00-df5b-11eb-8663-de86bfde9737.png)

**Comment by XxLittleCxX** [comment]
请检查下载是否完整

**Comment by Leolhys** [comment]
额，我是从在线构建里下载的，下载的完整性怎么判断

**Comment by XxLittleCxX** [comment]
有没有下载到一半突然断了 或者你再试一下构建并下载 如果还不行 请点击分享按钮并提供链接

**Comment by Leolhys** [comment]
谢谢，解决了，自带浏览器的锅，这shit的safari

**Comment by Dianliang233** [comment]
cannot reproduce on 1.16.210.05

**Comment by Leolhys** [comment]
emmmm，请问这糟糕的蓝色UI怎么去

**Comment by EternityXuNuo** [comment]
建构里可选

**Comment by XxLittleCxX** [comment]
![image](http://gchat.qpic.cn/gchatpic_new/1445957253/657876815-3034588586-7168BBA10242D79759DDA662C3EEFAA1/0?term=3)
请检查有无选中此模块
