### ISSUE TITLE
因歌曲长度不一致而导致的红石自动播放机工作不正常的问题

### ISSUE THREAD

**Issue by RxinnotRstar** [Teahouse-Studios/mcwzh-meme-resourcepack-bedrock#24]
**描述**
自动轮播唱片的时候，因为唱片机本来记录的唱片长度与梗体中文唱片包更改后的唱片长度不同，导致部分唱片没播完就轮到下一张，部分唱片播完了却不立即切换到下一张。

**复现步骤**
安装梗体中文唱片包
制作一台自动播放机，然后放入不同的唱片
戴好耳机

**版本**
与版本无关，任何版本都会出现。

**其他内容**
修复这个问题时可以试试看重新指定唱片机记录的音乐时长。
玩家在服务器游玩时需要忽略这个问题。

**Comment by lakejason0** [comment]
基岩版不熟，主催不在，如果会附加包的话pr welcome

**Comment by Dianliang233** [comment]
自动唱片机是你玩家自己做的啊……

**Comment by RxinnotRstar** [comment]
> 
> 
> 自动唱片机是你玩家自己做的啊……

唱片机在播放原版音乐的时候是可以正常下一曲的，而替换过了之后是因为长度对不上导致报道有误差。

**Comment by Dianliang233** [comment]
那就需要你自己调整长度了

**Comment by SkyEye-FAST** [comment]
所谓的自动唱片机是您自己在游戏里做的？
不懂就问，这与我们又有何干？难不成您做的手机壳套不到手机上，反倒要怪手机大小不匹配您的手机壳吗？

**Comment by SkyEye-FAST** [comment]
@RxinnotRstar 劳烦问一下您制作的自动唱片机原理

**Comment by RxinnotRstar** [comment]
> @RxinnotRstar 劳烦问一下您制作的自动唱片机原理

原理：
根据唱片机特性，唱片播放的时候能输出红石信号，于是我利用红石中继器、漏斗、红石粉、投掷器制作了一个能让唱片自动播放的装置。在唱片播放时漏斗被锁定，唱片播放完毕后因为停止输出红石信号而漏斗解锁，唱片机下方的漏斗吸出唱片的同时上方的漏斗放入唱片，唱片机因此可以继续播放另一张唱片。相关的视频我会在这几天录制并上传，届时会发视频链接到本issue。

我在关闭唱片资源包的时候使用自动唱片机播放不同的唱片，唱片机正常工作，能在正确的时间释放唱片。而替换唱片资源之后就会出现音乐被提前切换或者播放完毕之后等待一段时间才会切换的情况。我认为这是由于替换后的音乐时长与原版音乐时长不一致，而唱片机是根据原版音乐的时长停止输出红石信号的，这才导致了报道有偏差。同时希望您不要以过激的态度对待用户，良好的沟通是发扬梗体中文的开始。

**Comment by RxinnotRstar** [comment]
> 那就需要你自己调整长度了

我认为这个是写死在唱片机的程序里面的，所以我无法调节长度。

**Comment by lakejason0** [comment]
要么我们找到证据，证明他是硬编码，那么我们无能为力；
要么我们找到证据，证明附加包修改唱片可以填入唱片的长度元数据，然后有人会的话pr welcome。

**Comment by RxinnotRstar** [comment]
> 要么我们找到证据，证明他是硬编码，那么我们无能为力；
> 要么我们找到证据，证明附加包修改唱片可以填入唱片的长度元数据，然后有人会的话pr welcome。

好的，谢谢！

**Comment by lakejason0** [comment]
有人提出“剪辑音乐使得长度符合原来音乐的长度”……
我想说这种要求不是很合理（虽然最一开始听起来好像没问题），考虑到每个作品的篇幅不一，贸然的剪辑很可能会导致体验下降（PJSK剪的六兆年那阴间的，对吧）。我们这里擅长基岩版附加开发的不算太多，我自己去bedrock.dev似乎也没找到有相关的数据驱动部分，如果这个部分真的是完全硬编码的（这意味着“修复”这个问题必须要剪辑），那么我更倾向于不会修复，因为贸然剪辑会导致体验下降。修改音乐符合原本文件的长度并且不丧失游戏体验不是我们轻易就能做到的事情，也希望您能谅解。

**Comment by lakejason0** [comment]
这个issue暂以won't fix关闭，待有更成熟的解决方案后方可重新开启。

**Comment by RxinnotRstar** [comment]
> 
> 
> 这个issue暂以won't fix关闭，待有更成熟的解决方案后方可重新开启。

推荐使用“请求帮助”、“推迟”标签。

您提醒我了，或许我可以试试看剪辑音乐来暂时缓解这个问题。
剪辑音乐还可以避免因为时长不一致导致多人游戏时未安装梗体中文唱片包和安装了的玩家的唱片冲突，除非能够做到检测到多人游戏之后禁用这个设定。
我将会尝试剪辑音乐文件（剪掉开头结尾、重复某些片段……）来增减时长，尽管成功率很小。请问我应该在哪里 pr 唱片包？

**Comment by XxLittleCxX** [comment]
哦 那目前是 private 仓库 我待会问问能不能公开

如果你马上做完的话 你可以打包后找个地方上传 然后发上来 

if you can

**Comment by Dianliang233** [comment]
。link

**Comment by Dianliang233** [comment]
不可以公开，DMCA

**Comment by SkyEye-FAST** [comment]
> > @RxinnotRstar 劳烦问一下您制作的自动唱片机原理
> 
> 原理：
> 根据唱片机特性，唱片播放的时候能输出红石信号，于是我利用红石中继器、漏斗、红石粉、投掷器制作了一个能让唱片自动播放的装置。在唱片播放时漏斗被锁定，唱片播放完毕后因为停止输出红石信号而漏斗解锁，唱片机下方的漏斗吸出唱片的同时上方的漏斗放入唱片，唱片机因此可以继续播放另一张唱片。
> 我在关闭唱片资源包的时候使用自动唱片机播放不同的唱片，唱片机正常工作，能在正确的时间释放唱片。而替换唱片资源之后就会出现音乐被提前切换或者播放完毕之后等待一段时间才会切换的情况。我认为这是由于替换后的音乐时长与原版音乐时长不一致，而唱片机是根据原版音乐的时长停止输出红石信号的，这才导致了报道有偏差。同时希望您不要以过激的态度对待用户，良好的沟通是发扬梗体中文的开始。

我**不认为**我先前的言行举止存在所谓”过激的态度“；以及，我认为”发扬梗体中文的开始“与”良好的沟通“无关。

首先，您所言的”发扬“一词存在用词错误。”发扬“一词在《现代汉语词典》中存在以下解释：

> 1.发展和提倡（优良作风、传统等）：～光大；～民主；～勤俭节约、艰苦奋斗的精神。
> 2.发挥：～火力，消灭敌人。

由此，”梗体中文“一词接在”发扬“之后显然欠妥。

其次，”发扬梗体中文的开始“必然是**确保梗体中文有良好的质量**，而非”良好的沟通“。
”沟通“一词在汉语中意为”使两方能通连“，词性为动词；而您所述的”沟通“显然对应的是英文中的”communication“一词，属于欧化中文。
当然，这一点对于你我的”沟通“来说无可厚非。
退一步来说，在”良好的沟通“前，更重要的是”有效的反馈“。我并不认为您反馈了一个有效的问题。
即便如此，仍然得要感谢您的反馈。

不管怎样，如果我的言行冒犯到了您，那我在此向您表示诚挚的歉意。

**Comment by lakejason0** [comment]
好吧，先开着；我和SEF在可预见的未来没有时间管理这些项目；如果有进展的话请再次报告。

**Comment by SkyEye-FAST** [comment]
不活跃，若有必要请reopen。

**Comment by RxinnotRstar** [comment]
我有个想法……
只保留歌曲的主要部分，把其余的全部剪掉
例如脑力只保留“let the bass……”及后面的部分

**Comment by DrLee-lihr** [comment]
> 我有个想法…… 大部分人应该都只需要听到主要部分就可以了 那么我们就可以只保留歌曲的主要部分，把其余的全部剪掉，保证剪辑后的歌曲小于原版的时长 例如脑力只保留“let the bass……”及后面的部分 我晚点会在这里上传一份剪过的歌曲的压缩包

🤔我觉得很多歌前面也很灵魂 剪一半是不是不太好

**Comment by RxinnotRstar** [comment]
[https://rxinns.lanzouj.com/iQFqc04mhogj](url)
不知道为什么我上传不了zip到这里

**Comment by Dianliang233** [comment]
请新建 issue
