### ISSUE TITLE
是否愿意在语言文件内加入品牌/商标名？

### ISSUE THREAD

**Issue by RxinnotRstar** [Teahouse-Studios/mcwzh-meme-resourcepack-bedrock#25]
我观察到梗体中文内有一个“TARGET®”，特此提问。如果愿意，我将会在不久之后进行pull request。
已经被梗化的内容将优先不进行更改。

**Comment by lakejason0** [comment]
这种属于完全一致的所以玩了个梗，其他的品牌非必要不添加
