### ISSUE TITLE
因歌曲长度不一致而导致的红石自动播放机工作不正常的问题 - 续

### ISSUE THREAD

**Issue by RxinnotRstar** [Teahouse-Studios/mcwzh-meme-resourcepack-bedrock#29]
前言：https://github.com/Teahouse-Studios/mcwzh-meme-resourcepack-bedrock/issues/24
修改后的歌曲剪辑：https://rxinns.lanzouj.com/iQFqc04mhogj

**Comment by RxinnotRstar** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Rxinns/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Rxinns/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



歌名 | 长度
-- | --
11 | 1:11
mellohi | 1:36
pigstep | 2:28
stal | 2:30
far | 2:54
13 | 2:58
cat | 3:05
chirp | 3:05
strad | 3:08
mall | 3:17
wait | 3:57
ward | 4:11
blocks | 5:45



</body>

</html>

**Comment by Dianliang233** [comment]
我觉得不行

**Comment by RxinnotRstar** [comment]
我想了一下，11号唱片还是不要剪比较好……

**Comment by DrLee-lihr** [comment]
我认为这是 Mojang 的事
如果 confirm 了 建议发到 Mojira 让 Mojang 去把这个时长问题修掉
（因为我没有基岩版 所以无法测试）
