### ISSUE TITLE
README.md有链接失效了

### ISSUE THREAD

**Issue by kaoyu555666777** [Teahouse-Studios/mcwzh-meme-resourcepack-bedrock#35]
关于Minecraft基岩版的全语言修正，参见俄语Crowdin校对员fromgate制作的[Translations for Minecraft (Bedrock)](https://www.curseforge.com/minecraft/mc-addons/translations-for-minecraft)

这句话https://www.curseforge.com/minecraft/mc-addons/translations-for-minecraft链接失效

**Comment by DoroWolf** [comment]
已修復
