### ISSUE TITLE
加入贴图和音效更新

### ISSUE THREAD

**Issue by Wishing-Qi** [Teahouse-Studios/mcwzh-meme-resourcepack-bedrock#7]
如题，某些物品可以添加新材质，（不过三叉戟的材质换给盔甲架比较好吧喂），然后可以给诸如流浪奸商添加疯狂代夫的音效（名字我会改的

**Comment by lakejason0** [comment]
音效？音效建议同步Java版的过来。

**Comment by SkyEye-FAST** [comment]
音效不建议替换，更不建议随便改成其他游戏的音效。
至于材质……替换给三叉戟是有原因的，也不建议随便把其他游戏的贴图拿来用。

**Comment by lakejason0** [comment]
原因：没得换了。

**Comment by Wishing-Qi** [comment]
> 
> 
> 音效不建议替换，更不建议随便改成其他游戏的音效。
> 至于材质……替换给三叉戟是有原因的，也不建议随便把其他游戏的贴图拿来用。

其他游戏的贴图也没法直接用吧……我指的是就比如那个面包，抽象一个野兽先辈在上面，就类似这种的小改动

**Comment by lakejason0** [comment]
> > 音效不建议替换，更不建议随便改成其他游戏的音效。
> > 至于材质……替换给三叉戟是有原因的，也不建议随便把其他游戏的贴图拿来用。
> 
> 其他游戏的贴图也没法直接用吧……我指的是就比如那个面包，抽象一个野兽先辈在上面，就类似这种的小改动

后期做模块化我觉得可以加类似于这种的……野兽面包还是算了吧。

**Comment by Wishing-Qi** [comment]
狗头保命

**Comment by AlPha5130** [comment]
> 后期做模块化我觉得可以加类似于这种的……野兽面包还是算了吧。

项目已于今天（2020-6-21）基本完成了模块化。
